// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartShoppingAssistant.DataAccess;

#nullable disable

namespace SmartShoppingAssistant.DataAccess.Migrations
{
    [DbContext(typeof(SmartShoppingAssistantDbContext))]
    [Migration("20260613180427_WorldCupThemeSeed")]
    partial class WorldCupThemeSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems", (string)null);
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Tricouri naționale și echipament de joc",
                            Name = "Tricouri & Echipament"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mingi oficiale și accesorii de antrenament",
                            Name = "Mingi & Antrenament"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fulare, steaguri, șepci și accesorii pentru suporteri",
                            Name = "Accesorii Fani"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Stickere, trofee, mascote și figurine",
                            Name = "Colecționabile"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Gustări și băuturi pentru seara meciului",
                            Name = "Snacks & Băuturi"
                        });
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Tricou oficial replica, ediția Cupa Mondială",
                            ImageUrl = "https://loremflickr.com/400/400/argentina,jersey,football?lock=1",
                            Name = "Tricou Național Argentina",
                            Price = 249.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Tricou oficial replica, ediția Cupa Mondială",
                            ImageUrl = "https://loremflickr.com/400/400/brazil,jersey,football?lock=2",
                            Name = "Tricou Național Brazilia",
                            Price = 249.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Tricou oficial replica, ediția Cupa Mondială",
                            ImageUrl = "https://loremflickr.com/400/400/france,jersey,soccer?lock=3",
                            Name = "Tricou Național Franța",
                            Price = 239.99m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Tricou suporter, ediție specială",
                            ImageUrl = "https://loremflickr.com/400/400/jersey,football,red?lock=4",
                            Name = "Tricou Național România",
                            Price = 219.99m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Șort de joc, material respirabil",
                            ImageUrl = "https://loremflickr.com/400/400/football,shorts,sport?lock=5",
                            Name = "Șort Fotbal Pro",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Jambiere de joc, mărime universală",
                            ImageUrl = "https://loremflickr.com/400/400/football,socks,sport?lock=6",
                            Name = "Jambiere Fotbal",
                            Price = 39.99m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Replica mingii oficiale de turneu",
                            ImageUrl = "https://loremflickr.com/400/400/soccer,ball?lock=7",
                            Name = "Minge Oficială Cupa Mondială",
                            Price = 179.99m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Minge rezistentă pentru antrenamente",
                            ImageUrl = "https://loremflickr.com/400/400/football,ball,training?lock=8",
                            Name = "Minge Antrenament",
                            Price = 69.99m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Pompă pentru mingi cu indicator de presiune",
                            ImageUrl = "https://loremflickr.com/400/400/ball,pump?lock=9",
                            Name = "Pompă cu Manometru",
                            Price = 34.99m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Set 20 conuri pentru exerciții",
                            ImageUrl = "https://loremflickr.com/400/400/training,cones,football?lock=10",
                            Name = "Set Conuri Antrenament",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 11,
                            Description = "Fular tricotat pentru tribună",
                            ImageUrl = "https://loremflickr.com/400/400/scarf,football,fan?lock=11",
                            Name = "Fular Suporter",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = 12,
                            Description = "Steag 150x90cm pentru suporteri",
                            ImageUrl = "https://loremflickr.com/400/400/flag,stadium,fans?lock=12",
                            Name = "Steag Mare Național",
                            Price = 44.99m
                        },
                        new
                        {
                            Id = 13,
                            Description = "Șapcă cu cozoroc, ediție turneu",
                            ImageUrl = "https://loremflickr.com/400/400/cap,hat,sport?lock=13",
                            Name = "Șapcă Suporter",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 14,
                            Description = "Set vopsele pentru susținere la stadion",
                            ImageUrl = "https://loremflickr.com/400/400/facepaint,fan,football?lock=14",
                            Name = "Vopsea Față Tricolor",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 15,
                            Description = "Trompetă pentru atmosfera din tribună",
                            ImageUrl = "https://loremflickr.com/400/400/vuvuzela,stadium,fans?lock=15",
                            Name = "Trompetă Suporter",
                            Price = 24.99m
                        },
                        new
                        {
                            Id = 16,
                            Description = "Album oficial pentru colecția de stickere",
                            ImageUrl = "https://loremflickr.com/400/400/sticker,album,collection?lock=16",
                            Name = "Album Stickere Mondial",
                            Price = 39.99m
                        },
                        new
                        {
                            Id = 17,
                            Description = "Replică decorativă a trofeului",
                            ImageUrl = "https://loremflickr.com/400/400/trophy,gold,football?lock=17",
                            Name = "Replică Trofeu Aurit",
                            Price = 129.99m
                        },
                        new
                        {
                            Id = 18,
                            Description = "Mascota oficială a turneului, de pluș",
                            ImageUrl = "https://loremflickr.com/400/400/mascot,plush,toy?lock=18",
                            Name = "Mascotă de Pluș",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 19,
                            Description = "Bax 6 sticle pentru seara meciului",
                            ImageUrl = "https://loremflickr.com/400/400/beer,bottles?lock=19",
                            Name = "Set 6 Beri Blonde",
                            Price = 34.99m
                        },
                        new
                        {
                            Id = 20,
                            Description = "Pungă mare de chipsuri pentru petrecere",
                            ImageUrl = "https://loremflickr.com/400/400/chips,snacks?lock=20",
                            Name = "Chipsuri Party Mix",
                            Price = 14.99m
                        },
                        new
                        {
                            Id = 21,
                            Description = "Set 3 pungi popcorn, gata în 3 minute",
                            ImageUrl = "https://loremflickr.com/400/400/popcorn,snack?lock=21",
                            Name = "Popcorn pentru Microunde",
                            Price = 8.99m
                        },
                        new
                        {
                            Id = 22,
                            Description = "Bax 6 doze băuturi carbogazoase",
                            ImageUrl = "https://loremflickr.com/400/400/soda,drinks,cans?lock=22",
                            Name = "Set 6 Băuturi Răcoritoare",
                            Price = 29.99m
                        });
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.ProductCategory", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategories", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 21,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 22,
                            CategoryId = 5
                        });
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Reward")
                        .HasColumnType("int");

                    b.Property<int>("RewardValue")
                        .HasColumnType("int");

                    b.Property<decimal>("Threshold")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductId");

                    b.ToTable("Promotions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "Cumpără 3 tricouri, cel mai ieftin e gratis",
                            Reward = 0,
                            RewardValue = 1,
                            Threshold = 3m,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "10% reducere la comenzi peste 300 RON",
                            Reward = 1,
                            RewardValue = 10,
                            Threshold = 300.00m,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            IsActive = true,
                            Name = "3 accesorii fani — cel mai ieftin gratis",
                            Reward = 0,
                            RewardValue = 1,
                            Threshold = 3m,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 5,
                            IsActive = true,
                            Name = "Pachet meci: la 4 snacks, 1 gratis",
                            Reward = 0,
                            RewardValue = 1,
                            Threshold = 4m,
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Seara finalei: 15% la comenzi peste 500 RON",
                            Reward = 1,
                            RewardValue = 15,
                            Threshold = 500.00m,
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "5% reducere la comenzi peste 150 RON",
                            Reward = 1,
                            RewardValue = 5,
                            Threshold = 150.00m,
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "2+ mingi oficiale: 15% reducere",
                            ProductId = 7,
                            Reward = 1,
                            RewardValue = 15,
                            Threshold = 2m,
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "Cumpără 5 Chipsuri Party Mix, 1 gratis",
                            ProductId = 20,
                            Reward = 0,
                            RewardValue = 1,
                            Threshold = 5m,
                            Type = 0
                        });
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.CartItem", b =>
                {
                    b.HasOne("SmartShoppingAssistant.DataAccess.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartShoppingAssistant.DataAccess.Entities.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.ProductCategory", b =>
                {
                    b.HasOne("SmartShoppingAssistant.DataAccess.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartShoppingAssistant.DataAccess.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Promotion", b =>
                {
                    b.HasOne("SmartShoppingAssistant.DataAccess.Entities.Category", "Category")
                        .WithMany("Promotions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartShoppingAssistant.DataAccess.Entities.Product", "Product")
                        .WithMany("Promotions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Category", b =>
                {
                    b.Navigation("Promotions");
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Promotions");
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.User", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
