// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartShoppingAssistant.DataAccess;

#nullable disable

namespace SmartShoppingAssistant.DataAccess.Migrations
{
    [DbContext(typeof(SmartShoppingAssistantDbContext))]
    [Migration("20260613191058_WorldCupCatalog")]
    partial class WorldCupCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems", (string)null);
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Tricouri oficiale ale echipelor naționale, Cupa Mondială 2026",
                            Name = "Tricouri Naționale"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mingi oficiale Trionda și accesorii de joc",
                            Name = "Mingi & Echipament"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fulare și șepci pentru suporteri",
                            Name = "Accesorii Fani"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Mascote de pluș și stickere Panini",
                            Name = "Colecționabile"
                        });
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/image_ab8f6ea2-c16a-4882-822e-aa52e9506054.png?width=533",
                            Name = "Tricou Național Argentina",
                            Price = 259.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/image_02047e33-3b4e-41f2-869b-ac361dd4b283.png?width=533",
                            Name = "Tricou Național Brazilia",
                            Price = 259.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/image_f7f029ac-d57c-4aab-ab4e-45d5d056ac29.jpg?width=533",
                            Name = "Tricou Național Franța",
                            Price = 249.99m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/image_b3db0408-344c-4ba2-b34b-5bedc55c84f1.png?width=533",
                            Name = "Tricou Național Spania",
                            Price = 249.99m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/image_54f59fd1-10b1-4430-b581-a46bbd87255c.jpg?width=533",
                            Name = "Tricou Național Anglia",
                            Price = 249.99m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/KD8363_1_APPAREL_Photography_FrontCenterView_white.jpg?width=533",
                            Name = "Tricou Național Germania",
                            Price = 249.99m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/FIFAMZ0368-1.png?width=533",
                            Name = "Tricou Național Portugalia",
                            Price = 249.99m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/image_c78fa204-51ce-440a-a410-c8b8a4258deb.jpg?width=533",
                            Name = "Tricou Național Statele Unite",
                            Price = 239.99m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/image_09d4d8ad-c993-4e39-af1c-caed11623a11.png?width=533",
                            Name = "Tricou Național Mexic",
                            Price = 239.99m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/image_3bf28b9c-e9f3-49e3-ac48-fd7473b92b15.png?width=533",
                            Name = "Tricou Național Italia",
                            Price = 249.99m
                        },
                        new
                        {
                            Id = 11,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/image_0cf9c430-1214-48a1-a3ee-cfd8b32a882c.png?width=533",
                            Name = "Tricou Național Belgia",
                            Price = 239.99m
                        },
                        new
                        {
                            Id = 12,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/image_695e8c00-a951-4ed8-af81-899e39ed5503.png?width=533",
                            Name = "Tricou Național Columbia",
                            Price = 229.99m
                        },
                        new
                        {
                            Id = 13,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/image_1a0d5dda-c1e6-4621-9fa7-c0079d201af8.jpg?width=533",
                            Name = "Tricou Național Nigeria",
                            Price = 229.99m
                        },
                        new
                        {
                            Id = 14,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/FIFAMZ0420-1.png?width=533",
                            Name = "Tricou Național Paraguay",
                            Price = 219.99m
                        },
                        new
                        {
                            Id = 15,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/KY2217_1_APPAREL_Photography_FrontCenterView_white.jpg?width=533",
                            Name = "Tricou Național Africa de Sud",
                            Price = 219.99m
                        },
                        new
                        {
                            Id = 16,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://flagcdn.com/w320/nl.png",
                            Name = "Tricou Național Țările de Jos",
                            Price = 239.99m
                        },
                        new
                        {
                            Id = 17,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://flagcdn.com/w320/hr.png",
                            Name = "Tricou Național Croația",
                            Price = 229.99m
                        },
                        new
                        {
                            Id = 18,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://flagcdn.com/w320/uy.png",
                            Name = "Tricou Național Uruguay",
                            Price = 229.99m
                        },
                        new
                        {
                            Id = 19,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://flagcdn.com/w320/ca.png",
                            Name = "Tricou Național Canada",
                            Price = 229.99m
                        },
                        new
                        {
                            Id = 20,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://flagcdn.com/w320/jp.png",
                            Name = "Tricou Național Japonia",
                            Price = 229.99m
                        },
                        new
                        {
                            Id = 21,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://flagcdn.com/w320/kr.png",
                            Name = "Tricou Național Coreea de Sud",
                            Price = 219.99m
                        },
                        new
                        {
                            Id = 22,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://flagcdn.com/w320/ma.png",
                            Name = "Tricou Național Maroc",
                            Price = 219.99m
                        },
                        new
                        {
                            Id = 23,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://flagcdn.com/w320/sn.png",
                            Name = "Tricou Național Senegal",
                            Price = 219.99m
                        },
                        new
                        {
                            Id = 24,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://flagcdn.com/w320/gh.png",
                            Name = "Tricou Național Ghana",
                            Price = 209.99m
                        },
                        new
                        {
                            Id = 25,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://flagcdn.com/w320/cm.png",
                            Name = "Tricou Național Camerun",
                            Price = 209.99m
                        },
                        new
                        {
                            Id = 26,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://flagcdn.com/w320/ci.png",
                            Name = "Tricou Național Coasta de Fildeș",
                            Price = 209.99m
                        },
                        new
                        {
                            Id = 27,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://flagcdn.com/w320/eg.png",
                            Name = "Tricou Național Egipt",
                            Price = 209.99m
                        },
                        new
                        {
                            Id = 28,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://flagcdn.com/w320/tn.png",
                            Name = "Tricou Național Tunisia",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = 29,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://flagcdn.com/w320/dz.png",
                            Name = "Tricou Național Algeria",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = 30,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://flagcdn.com/w320/au.png",
                            Name = "Tricou Național Australia",
                            Price = 219.99m
                        },
                        new
                        {
                            Id = 31,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://flagcdn.com/w320/sa.png",
                            Name = "Tricou Național Arabia Saudită",
                            Price = 209.99m
                        },
                        new
                        {
                            Id = 32,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://flagcdn.com/w320/ir.png",
                            Name = "Tricou Național Iran",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = 33,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://flagcdn.com/w320/qa.png",
                            Name = "Tricou Național Qatar",
                            Price = 209.99m
                        },
                        new
                        {
                            Id = 34,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://flagcdn.com/w320/ec.png",
                            Name = "Tricou Național Ecuador",
                            Price = 209.99m
                        },
                        new
                        {
                            Id = 35,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://flagcdn.com/w320/pe.png",
                            Name = "Tricou Național Peru",
                            Price = 209.99m
                        },
                        new
                        {
                            Id = 36,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://flagcdn.com/w320/cl.png",
                            Name = "Tricou Național Chile",
                            Price = 219.99m
                        },
                        new
                        {
                            Id = 37,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://flagcdn.com/w320/dk.png",
                            Name = "Tricou Național Danemarca",
                            Price = 229.99m
                        },
                        new
                        {
                            Id = 38,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://flagcdn.com/w320/ch.png",
                            Name = "Tricou Național Elveția",
                            Price = 229.99m
                        },
                        new
                        {
                            Id = 39,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://flagcdn.com/w320/pl.png",
                            Name = "Tricou Național Polonia",
                            Price = 229.99m
                        },
                        new
                        {
                            Id = 40,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://flagcdn.com/w320/rs.png",
                            Name = "Tricou Național Serbia",
                            Price = 219.99m
                        },
                        new
                        {
                            Id = 41,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://flagcdn.com/w320/at.png",
                            Name = "Tricou Național Austria",
                            Price = 219.99m
                        },
                        new
                        {
                            Id = 42,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://flagcdn.com/w320/gb-sct.png",
                            Name = "Tricou Național Scoția",
                            Price = 229.99m
                        },
                        new
                        {
                            Id = 43,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://flagcdn.com/w320/gb-wls.png",
                            Name = "Tricou Național Țara Galilor",
                            Price = 219.99m
                        },
                        new
                        {
                            Id = 44,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://flagcdn.com/w320/no.png",
                            Name = "Tricou Național Norvegia",
                            Price = 229.99m
                        },
                        new
                        {
                            Id = 45,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://flagcdn.com/w320/se.png",
                            Name = "Tricou Național Suedia",
                            Price = 229.99m
                        },
                        new
                        {
                            Id = 46,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://flagcdn.com/w320/tr.png",
                            Name = "Tricou Național Turcia",
                            Price = 219.99m
                        },
                        new
                        {
                            Id = 47,
                            Description = "Tricou oficial replica, ediția Cupa Mondială 2026",
                            ImageUrl = "https://flagcdn.com/w320/ua.png",
                            Name = "Tricou Național Ucraina",
                            Price = 219.99m
                        },
                        new
                        {
                            Id = 48,
                            Description = "Tricou suporter România, ediția Cupa Mondială 2026",
                            ImageUrl = "https://flagcdn.com/w320/ro.png",
                            Name = "Tricou Național România",
                            Price = 219.99m
                        },
                        new
                        {
                            Id = 49,
                            Description = "Replica mingii oficiale de turneu Trionda",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/image_9c1a59b6-9fe5-480d-845d-b77dfc2c839c.png?width=533",
                            Name = "Minge Oficială Trionda",
                            Price = 179.99m
                        },
                        new
                        {
                            Id = 50,
                            Description = "Minge de joc Trionda Pro, performanță înaltă",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/image_acc6fba9-fdb5-46ad-8325-7c31b56ebd97.png?width=533",
                            Name = "Minge Trionda Pro",
                            Price = 149.99m
                        },
                        new
                        {
                            Id = 51,
                            Description = "Minge Trionda pentru competiție",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/image_b74b2afa-3620-4e7c-af50-00dcc69d343b.png?width=533",
                            Name = "Minge Trionda Competiție",
                            Price = 129.99m
                        },
                        new
                        {
                            Id = 52,
                            Description = "Mini-minge de colecție Trionda",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/image_cb4ed0a3-31c3-4106-be94-dceb214b7337.png?width=533",
                            Name = "Mini-minge Trionda",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = 53,
                            Description = "Mini-minge AFA Argentina, ediție turneu",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/FIFAEQ013000-1.jpg?width=533",
                            Name = "Mini-minge Argentina",
                            Price = 64.99m
                        },
                        new
                        {
                            Id = 54,
                            Description = "Mini-minge Mexic, ediție turneu",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/image_31911b92-ff2a-45f4-853b-0f7f5d6a229c.png?width=533",
                            Name = "Mini-minge Mexic",
                            Price = 64.99m
                        },
                        new
                        {
                            Id = 55,
                            Description = "Breloc decorativ în formă de minge",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/Untitleddesign_2.png?width=533",
                            Name = "Breloc Minge cu Sclipici",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 56,
                            Description = "Fular oficial suporter, ediția Cupa Mondială 2026",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/image_8e3e9958-8194-41ec-a67e-1ce56d64d40a.png?width=533",
                            Name = "Fular Mexic 'We Are'",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 57,
                            Description = "Fular oficial suporter, ediția Cupa Mondială 2026",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/image_59bb7189-4e92-4068-87b4-3caa8d17a2f6.png?width=533",
                            Name = "Fular Anglia 'We Are'",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 58,
                            Description = "Fular oficial suporter, ediția Cupa Mondială 2026",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/image_1c549abc-9b97-4f9f-b28f-aa2bd3c125c2.jpg?width=533",
                            Name = "Fular Franța 'We Are'",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 59,
                            Description = "Fular oficial suporter, ediția Cupa Mondială 2026",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/image_4d4a4fb6-d072-4612-9b1b-6133c55d2ee2.jpg?width=533",
                            Name = "Fular Spania 'We Are'",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 60,
                            Description = "Fular oficial suporter, ediția Cupa Mondială 2026",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/image_16a9dbc7-07fb-460c-a622-c74e47fbe5c2.jpg?width=533",
                            Name = "Fular Portugalia 'We Are'",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 61,
                            Description = "Fular oficial suporter, ediția Cupa Mondială 2026",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/image_8fabf9f0-77e6-4532-9ab6-134da3792d3b.jpg?width=533",
                            Name = "Fular Germania 'We Are'",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 62,
                            Description = "Fular cu designul oficial al turneului",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/image_94d81176-cac3-4b5f-9828-d8171386f304.png?width=533",
                            Name = "Fular Turneu Oficial",
                            Price = 69.99m
                        },
                        new
                        {
                            Id = 63,
                            Description = "Șapcă oficială echipa națională",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/France_4.jpg?width=533",
                            Name = "Șapcă Franța",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 64,
                            Description = "Șapcă oficială echipa națională",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/Brazil_3.jpg?width=533",
                            Name = "Șapcă Brazilia",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 65,
                            Description = "Șapcă oficială echipa națională",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/Mexico_4.jpg?width=533",
                            Name = "Șapcă Mexic",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 66,
                            Description = "Șapcă oficială echipa națională",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/England_3.jpg?width=533",
                            Name = "Șapcă Anglia",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 67,
                            Description = "Șapcă oficială echipa națională",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/Croatia_3.jpg?width=533",
                            Name = "Șapcă Croația",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 68,
                            Description = "Mascota oficială a turneului, varianta USA",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/image_45665d36-9cd6-403e-9029-a8ad77c8379c.jpg?width=533",
                            Name = "Mascotă de Pluș USA 25cm",
                            Price = 119.99m
                        },
                        new
                        {
                            Id = 69,
                            Description = "Mascota oficială a turneului, varianta Mexic",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/image_8c3712e0-ce68-4e13-adb2-9576753635f3.jpg?width=533",
                            Name = "Mascotă de Pluș Mexic 25cm",
                            Price = 119.99m
                        },
                        new
                        {
                            Id = 70,
                            Description = "Mascotă de pluș Squishmallows, varianta Canada",
                            ImageUrl = "https://store.fifa.com/cdn/shop/files/image_7ec8497a-6355-4871-8694-a6feec5af3c1.jpg?width=533",
                            Name = "Mascotă Squishmallows Canada",
                            Price = 99.99m
                        },
                        new
                        {
                            Id = 71,
                            Description = "Album Panini + plicuri de start, Cupa Mondială 2026",
                            ImageUrl = "https://www.panini.ro/media/catalog/product/0/0/005460baggexp_0_1.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=400&width=400&canvas=400:400",
                            Name = "Set Start Album Stickere",
                            Price = 24.99m
                        },
                        new
                        {
                            Id = 72,
                            Description = "Cutie completă cu 144 de plicuri Panini",
                            ImageUrl = "https://www.panini.ro/media/catalog/product/0/0/005460box144oe_0_en.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=400&width=400&canvas=400:400",
                            Name = "Cutie 144 Plicuri Stickere",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = 73,
                            Description = "Cutie metalică de colecție cu plicuri Panini",
                            ImageUrl = "https://www.panini.ro/media/catalog/product/b/u/bundle005460b50cptin_0.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=400&width=400&canvas=400:400",
                            Name = "Tin Colecție Stickere",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 74,
                            Description = "Bundle cu 50 de plicuri Panini",
                            ImageUrl = "https://www.panini.ro/media/catalog/product/b/u/bundle005460b7bexp50_0.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=400&width=400&canvas=400:400",
                            Name = "Pachet 50 Plicuri Stickere",
                            Price = 89.99m
                        });
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.ProductCategory", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategories", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 21,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 22,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 23,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 24,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 25,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 26,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 27,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 28,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 29,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 30,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 31,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 32,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 33,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 34,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 35,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 36,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 37,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 38,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 39,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 40,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 41,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 42,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 43,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 44,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 45,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 46,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 47,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 48,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 49,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 50,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 51,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 52,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 53,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 54,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 55,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 56,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 57,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 58,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 59,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 60,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 61,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 62,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 63,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 64,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 65,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 66,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 67,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 68,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 69,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 70,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 71,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 72,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 73,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 74,
                            CategoryId = 4
                        });
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Reward")
                        .HasColumnType("int");

                    b.Property<int>("RewardValue")
                        .HasColumnType("int");

                    b.Property<decimal>("Threshold")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductId");

                    b.ToTable("Promotions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "3 tricouri naționale — cel mai ieftin e gratis",
                            Reward = 0,
                            RewardValue = 1,
                            Threshold = 3m,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "5% reducere la comenzi peste 250 RON",
                            Reward = 1,
                            RewardValue = 5,
                            Threshold = 250.00m,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "10% reducere la comenzi peste 400 RON",
                            Reward = 1,
                            RewardValue = 10,
                            Threshold = 400.00m,
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Seara finalei: 15% la comenzi peste 700 RON",
                            Reward = 1,
                            RewardValue = 15,
                            Threshold = 700.00m,
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Super fan: 20% la comenzi peste 1000 RON",
                            Reward = 1,
                            RewardValue = 20,
                            Threshold = 1000.00m,
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            IsActive = true,
                            Name = "2 accesorii fani — al doilea e gratis",
                            Reward = 0,
                            RewardValue = 1,
                            Threshold = 2m,
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            IsActive = true,
                            Name = "3 colecționabile — cel mai ieftin e gratis",
                            Reward = 0,
                            RewardValue = 1,
                            Threshold = 3m,
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "Minge Oficială Trionda: 15% reducere",
                            ProductId = 49,
                            Reward = 1,
                            RewardValue = 15,
                            Threshold = 1m,
                            Type = 0
                        });
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.CartItem", b =>
                {
                    b.HasOne("SmartShoppingAssistant.DataAccess.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartShoppingAssistant.DataAccess.Entities.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.ProductCategory", b =>
                {
                    b.HasOne("SmartShoppingAssistant.DataAccess.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartShoppingAssistant.DataAccess.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Promotion", b =>
                {
                    b.HasOne("SmartShoppingAssistant.DataAccess.Entities.Category", "Category")
                        .WithMany("Promotions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartShoppingAssistant.DataAccess.Entities.Product", "Product")
                        .WithMany("Promotions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Category", b =>
                {
                    b.Navigation("Promotions");
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Promotions");
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAccess.Entities.User", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
